# Generated by Django 3.0.6 on 2020-06-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
