# Generated by Django 3.0.6 on 2020-06-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
